-- MySQL Script generated by MySQL Workbench
-- Sun Sep 24 00:00:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema customer
-- -----------------------------------------------------


USE `customer` ;

-- -----------------------------------------------------
-- Table `customer`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer`.`customer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NULL,
  `middlename` VARCHAR(50) NULL,
  `lastname` VARCHAR(100) NULL,
  `licence_number` VARCHAR(45) NULL,
  `licence_expiry` DATE NULL,
  `address1` VARCHAR(200) NULL,
  `address2` VARCHAR(100) NULL,
  `city` VARCHAR(60) NULL,
  `dob` DATE NULL,
  `type` VARCHAR(45) NULL,
  `mobile` VARCHAR(10) NULL,
  `alternate_number` VARCHAR(10) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customer`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `email` VARCHAR(60) NULL,
  `password` VARCHAR(60) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;